FROM ubuntu:22.04

RUN apt-get update && apt install -y nginx vim
RUN echo "\ndaemon off;" >> /etc//nginx/nginx.conf
RUN chown -R www-data:www-data /var/lib/nginx

COPY ./sampleapp/sampleapp/django.conf /etc/nginx/sites-available/django
RUN ln -s /etc/nginx/sites-available/django /etc/nginx/sites-enabled/django


WORKDIR /etc/nginx

CMD [ "nginx" ]

EXPOSE 80
EXPOSE 443