FROM nginx:latest

RUN apt-get update && apt-get -y install vim

#RUN echo "\ndaemon off;" >> /etc/nginx/nginx.conf
COPY ./nginx.conf /etc/nginx/nginx.conf

COPY ./sampleapp/sampleapp/django.conf /etc/nginx/sites-available/django
RUN /etc/nginx/sites-available/django
#RUN ls -n /etc/nginx/sites-available/django /etc/nginx/sites-enabled/django

CMD [ "nginx" ]

EXPOSE 80
EXPOSE 443
