# Generated by Django 4.2.3 on 2023-08-31 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Forum", "0003_topicgroupuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topicgroupuser",
            name="group",
            field=models.IntegerField(choices=[(0, "Common"), (1, "Admin")], default=0),
        ),
        migrations.AlterField(
            model_name="topicgroupuser",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="Forum.topic",
            ),
        ),
    ]
