name: call workflow

on:
    workflow_dispatch:

jobs:
    get-workflow-name:
        name: echo name
        runs-on: ubuntu-latest
        steps:
            - run: echo "This workflow is ${{ github.workflow }}"
    
    call-workflow:
        uses: ./.github/workflows/lesson4.yml
        with:
            person: syjoe