name : reusable workflow

on:
    workflow_call:
        inputs:
            person:
                required: true
                type: string


jobs:
    get-workflow-name:
        name: echo name
        runs-on: ubuntu-latest
        steps:
            - run: echo "This workflow is ${{ github.workflow }}"

    greeting:
        name : greeting
        runs-on: ubuntu-latest
        steps:
            - name: greeting
              run: echo "hello, ${{ inputs.person }}"