name: lesson1

on:
  push:
  pull_request:

jobs:
  echo-event:
    name: echo event
    runs-on: ubuntu-latest
    steps:
      - name: get event
        run: echo "This event is ${{github.event_name}}"

  docker-compose-build:
    name: docker compose build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
          cd lion_app
          docker build --tag lion-app .
