name: CD using Docker Image

on:
    push:
        branches:
            - 'main'

# env variable
env: 
    IMAGE_TAG: ${{ vars.NCP_REGISTRY }}/lion-app:latest

jobs:
    # Build Image / Push Image to NCR
    build-and-push:
        name: Build and Push Image
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Docker buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to NCR
              uses: docker/login-action@v2
              with:
                registry: ${{ vars.NCP_REGISTRY }}
                username: ${{ secrets.NCP_ACCESS_KEY_ID }}
                password: ${{ secrets.NCP_SECRET_KEY }}
            - name: Build and Push
              uses: docker/build-push-action@v4
              with:
                context: lion_app
                tags: ${{ env.IMAGE_TAG }}
                push: true
    
    # Pull Image From NCR / Run new container with new image
    deployment:
        needs: build-and-push
        name: Deploy to Server
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v3
            - name: pull and run the image
              uses: appleboy/ssh-action@v1.0.0
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                password: ${{ secrets.PASSWORD }}
                script: |
                    cd DevOps
                    docker login \
                    ${{ vars.NCP_REGISTRY }} \
                    -u ${{ secrets.NCP_ACCESS_KEY_ID }} \
                    -p ${{ secrets.NCP_SECRET_KEY }}
                    docker pull ${{ env.IMAGE_TAG }}
                    docker-compose -f docker-compose.prod.yml restart lion-app